version: '3.8'

services:

  db:
      image: postgres
      # platform: linux/amd64
      ports:
        - 5432:5432
      volumes: 
        - pgdata:/var/lib/postgresql/data
        - pgconf:/etc/postgresql
        - pglog:/var/log/postgresql
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      container_name: postgres_db
  selenium:
    image: selenium/standalone-firefox
    platform: linux/amd64
    ports:
    - 4444:4444
  app:
    build: .
    volumes:
      - .:/django
    
    ports:
      - 8000:8000
    image: app:django
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - selenium
volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog: 
    driver: local