# Generated by Django 3.1.7 on 2023-01-18 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_date', models.DateField()),
                ('title', models.CharField(max_length=140)),
                ('signed_amount', models.CharField(max_length=140)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.country')),
                ('sectors', models.ManyToManyField(to='scrap.Sector')),
            ],
        ),
    ]
